DROP TABLE IF EXISTS LIGNE;
DROP TABLE IF EXISTS COMMANDE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE CLIENT(
    idClient INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(20),
    ville VARCHAR(20)
)CHARACTER SET 'utf8';

CREATE TABLE ARTICLE(
    idArticle INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    designation VARCHAR(50),
    prix DECIMAL(5, 2)
)CHARACTER SET 'utf8';

CREATE TABLE COMMANDE(
    idCommande INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    dateCommande DATE,
    idClient INT,
    CONSTRAINT FK_COMMANDE_CLIENT FOREIGN KEY (idClient) REFERENCES CLIENT(idClient)
)CHARACTER SET 'utf8';

CREATE TABLE LIGNE(
    idLigne INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    idCommande INT,
    idArticle INT,
    CONSTRAINT FK_LIGNE_COMMANDE FOREIGN KEY (idCommande) REFERENCES COMMANDE(idCommande),
    CONSTRAINT FK_LIGNE_ARTICLE FOREIGN KEY (idArticle) REFERENCES ARTICLE(idArticle),
    quantite INT
)CHARACTER SET 'utf8';

LOAD DATA LOCAL INFILE '/Users/sephix/Documents/BUT_Info_Public/Semester_2/Database/TP/TP2/CLIENT.csv' INTO TABLE CLIENT CHARACTER SET utf8 FIELDS TERMINATED BY ';';
LOAD DATA LOCAL INFILE '/Users/sephix/Documents/BUT_Info_Public/Semester_2/Database/TP/TP2/COMMANDE.csv' INTO TABLE CLIENT CHARACTER SET utf8 FIELDS TERMINATED BY ';';
LOAD DATA LOCAL INFILE '/Users/sephix/Documents/BUT_Info_Public/Semester_2/Database/TP/TP2/LIGNE.csv' INTO TABLE CLIENT CHARACTER SET utf8 FIELDS TERMINATED BY ';';
LOAD DATA LOCAL INFILE '/Users/sephix/Documents/BUT_Info_Public/Semester_2/Database/TP/TP2/ARTICLE.csv' INTO TABLE CLIENT CHARACTER SET utf8 FIELDS TERMINATED BY ';';